sudo: required
language: node_js
node_js:
  - 14
services:
    -docker

before_install:
    # - gem install bundler --pre
    - docker build --network=host-t tobbyioa/docker-react -f Dockerfile.dev .

# script: 
#     - docker run tobbyioa/docker-react npm run test -- --coverage

script:
    - echo "skipping tests"

deploy: 
    provider: elaticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-806443812685"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $aws_access_key
    secret_access_key: 
        secure: "$aws_secret_key"