sudo: required
services:
    -docker

before_install:
    - gem install bundler --pre
    - docker build -t tobbyioa/docker-react -f Dockerfile.dev .

script: "rake"
#     - docker run tobbyioa/docker-react npm run test -- --coverage