version: '3.4' 
services: 
  web:
    stdin_open: true
    build:
      network: host
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "2525:2525"
    volumes:
      - /app/node_modules
      - .:/app
  # tests: 
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes: 
  #     - /app/node_modules
  #     - .:/app
  #   command: ["npm", "run","test"]


    
  